In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [7]:
## Load the dataset
data = pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [8]:
## Preprocess the data
## Drop irrelevent features/columns
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [9]:
## Encode categorical variables(convert into binary)
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [10]:
##---we cant categorize geography because it has 3 diff name so it will give 0,1,2 and for 2 it(ANN) assume that it is larger than other so not convinient to do so we apply diff technique i.e OHE

In [11]:
## One_Hot_Encode 'Geography'
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder_geo = OneHotEncoder()
geo_encoder = one_hot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [12]:
## converting into sparse matrix
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [13]:
one_hot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [14]:
geo_encoded_df = pd.DataFrame(geo_encoder.toarray(),columns = one_hot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [15]:
## Combine one hot encoder columns with original data
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [16]:
## Save the encoders and scaler
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('one_hot_encoder_geo.pkl','wb') as file:
    pickle.dump(one_hot_encoder_geo,file)

In [17]:
## Divide the dataset into independent and depedent features
X = data.drop('Exited', axis=1)
y = data['Exited']

## Split the data in training and testing set
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

## Scale these features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [18]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [19]:
with open ('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [20]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [21]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

WARNING:tensorflow:From d:\AI-Course\ANN Classification\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [22]:
X_train.shape
(X_train.shape[1],)

(12,)

In [23]:
## Build Our ANN Model
model = Sequential([
    Dense(64, activation = 'relu', input_shape = (X_train.shape[1],)), ## HL1 Connected with input layer
    Dense(32, activation ='relu'), ## HL2
    Dense(1, activation = 'sigmoid')  ## output layer
]
)

WARNING:tensorflow:From d:\AI-Course\ANN Classification\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [24]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [25]:
import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate = 0.01)
loss = tensorflow.keras.losses.BinaryCrossentropy()
loss

In [26]:
## Compile the model
model.compile(optimizer = opt, loss = "binary_crossentropy", metrics = ['accuracy'])

In [27]:
## Set up the TensorBoard
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
log_dir = "logs/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir = log_dir, histogram_freq = 1)

In [28]:
## Set up Early Stopping 
early_stopping_callback = EarlyStopping(monitor = 'val_loss', patience = 10,restore_best_weights = True) ## restore...-->during forward and backward p at which epoch you find best weight,consider that and reload it when u stop earlystopping, patience---> wait for 5 epochs and the stop

In [29]:
## Train the model
history = model.fit(
    X_train,y_train,validation_data = (X_test,y_test), epochs = 100, callbacks = [tensorflow_callback, early_stopping_callback]
)

Epoch 1/100
WARNING:tensorflow:From d:\AI-Course\ANN Classification\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From d:\AI-Course\ANN Classification\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 2s 4ms/step - loss: 0.4011 - accuracy: 0.8356 - val_loss: 0.3491 - val_accuracy: 0.8535
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3604 - accuracy: 0.8547 - val_loss: 0.3546 - val_accuracy: 0.8585
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3511 - accuracy: 0.8593 - val_loss: 0.3514 - val_accuracy: 0.8590
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3434 - accuracy: 0.8602 - val_loss: 0.3426 - val_accuracy: 0.8605
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3431 - accuracy: 0.8583 - val_loss: 0.3456 - val_accuracy: 0.8610
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3379 - accuracy: 0.8640 - val_loss: 0.3436 - val_accuracy: 0.8570
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3376 - accuracy: 0.8615 - val_loss: 0.3492 - val_accuracy: 0.8585
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3340 - accuracy: 0.8612 - val_loss: 0.3468 - val_accuracy: 0.8575
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3311 - accuracy: 0.8654 - val_loss: 0.3488 - val_accuracy: 0.8545
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3302 - accuracy: 0.8661 - val_loss: 0.3399 - val_accuracy: 0.8635
Epoch 11/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3261 - accuracy: 0.8670 - val_loss: 0.3412 - val_accuracy: 0.8560
Epoch 12/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3259 - accuracy: 0.8664 - val_loss: 0.3541 - val_accuracy: 0.8550
Epoch 13/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3211 - accuracy: 0.8674 - val_loss: 0.3405 - val_accuracy: 0.8655
Epoch 14/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3227 - accuracy: 0.8680 - val_loss: 0.3405 - val_accuracy: 0.8670
Epoch 15/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3190 - accuracy: 0.8705 - val_loss: 0.3494 - val_accuracy: 0.8605
Epoch 16/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3158 - accuracy: 0.8711 - val_loss: 0.3487 - val_accuracy: 0.8555
Epoch 17/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3139 - accuracy: 0.8725 - val_loss: 0.3604 - val_accuracy: 0.8540
Epoch 18/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3123 - accuracy: 0.8706 - val_loss: 0.3545 - val_accuracy: 0.8605
Epoch 19/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3128 - accuracy: 0.8716 - val_loss: 0.3639 - val_accuracy: 0.8565
Epoch 20/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3090 - accuracy: 0.8744 - val_loss: 0.3499 - val_accuracy: 0.8630

In [30]:
model.save('model.h5')

d:\AI-Course\ANN Classification\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [39]:
## Load TensorBoard Extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [1]:
%tensorboard --logdir logs\fit20261001-151141

UsageError: Line magic function `%tensorboard` not found.

In [33]:
import sys
print(sys.executable)

d:\AI-Course\ANN Classification\venv\python.exe

In [34]:
!python -m pip show tensorboard

Name: tensorboard
Version: 2.15.2
Summary: TensorBoard lets you watch Tensors Flow
Home-page: https://github.com/tensorflow/tensorboard
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: d:\AI-Course\ANN Classification\venv\Lib\site-packages
Requires: absl-py, google-auth, google-auth-oauthlib, grpcio, markdown, numpy, protobuf, requests, setuptools, six, tensorboard-data-server, werkzeug
Required-by: tensorflow-intel

In [2]:
import os
os.environ["TENSORBOARD_BINARY"] = r"D:\AI-Course\ANN Classification\venv\Scripts\tensorboard.exe"

In [36]:
import tensorflow as tf
print(tf.__version__)

2.15.0

In [37]:
%pip install tensorflow

Requirement already satisfied: tensorflow in .\venv\Lib\site-packages (2.15.0)
Requirement already satisfied: tensorflow-intel==2.15.0 in .\venv\Lib\site-packages (from tensorflow) (2.15.0)
Requirement already satisfied: absl-py>=1.0.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (2.5.0)
Requirement already satisfied: astunparse>=1.6.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (3.16.0)
Requirement already satisfied: libclang>=13.0.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (18.1.1)
Requirement already satisfied: ml-dtypes~=0.2.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (0.2.0)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.26.4)
Requirement already satisfied: opt-einsum>=2.3.2 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (3.4.0)
Requirement already satisfied: packaging in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (26.3)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (4.25.3)
Requirement already satisfied: setuptools in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (68.0.0)
Requirement already satisfied: six>=1.12.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (4.16.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.14.2)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (0.31.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.84.0)
Requirement already satisfied: tensorboard<2.16,>=2.15 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (2.15.2)
Requirement already satisfied: tensorflow-estimator<2.16,>=2.15.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (2.15.0)
Requirement already satisfied: keras<2.16,>=2.15.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (2.15.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in .\venv\Lib\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (2.59.1)
Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in .\venv\Lib\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (1.5.0)
Requirement already satisfied: markdown>=2.6.8 in .\venv\Lib\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.11)
Requirement already satisfied: requests<3,>=2.21.0 in .\venv\Lib\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (2.34.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in .\venv\Lib\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in .\venv\Lib\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.1.9)
Requirement already satisfied: pyasn1-modules>=0.2.1 in .\venv\Lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in .\venv\Lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (50.0.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in .\venv\Lib\site-packages (from google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (2.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.5.2)
Requirement already satisfied: idna<4,>=2.5 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (2026.7.22)
Requirement already satisfied: wheel<1.0,>=0.23.0 in .\venv\Lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.15.0->tensorflow) (0.47.0)
Requirement already satisfied: cffi>=2.0.0 in .\venv\Lib\site-packages (from cryptography>=38.0.3->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (2.1.1)
Requirement already satisfied: pycparser in .\venv\Lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in .\venv\Lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (0.6.4)
Requirement already satisfied: oauthlib>=3.0.0 in .\venv\Lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (4.0.0)
Requirement already satisfied: markupsafe>=2.1.1 in .\venv\Lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import sys
import tensorboard

print("Python:", sys.executable)
print("TensorBoard:", tensorboard.__version__)
print("TensorBoard location:", tensorboard.__file__)

Python: d:\AI-Course\ANN Classification\venv\python.exe
TensorBoard: 2.15.2
TensorBoard location: d:\AI-Course\ANN Classification\venv\Lib\site-packages\tensorboard\__init__.py

In [ ]:
## Load the pickle file